# main-project/compose.yaml
services:
  webapp:
    extends:
      file: ../commons/common.yaml # Wskazuje na plik w katalogu nadrzędnym/sąsiednim
      service: base
    command: ["sh", "-c", "env | grep COMMON"]
