# main-project/compose.yaml
services:
  webapp:
    extends:
      file: ../commos/common.yaml # Wskazuje na plik w katalogu nadrzędnym/sąsiednim
      service: base
    command: ["sh", "-c", "echo COMMON_VAR is: $COMMON_VAR"]
