pipeline {
    agent any
    stages {
        stage('Build') { // Przykładowa nazwa etapu, zmień jeśli trzeba
            steps {
                sh 'make all' // Dodano krok: wykonanie polecenia 'make all'
                // Lub po prostu 'make', jeśli 'all' jest domyślnym celem
            }
        }
        stage('Test') {
            steps {
                sh 'make check'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'target/app.jar', fingerprint: true
            }
        }
        stage('Publish') { // Jeśli masz taki etap
            steps {
                sh 'make publish'
            }
        }
        // ... inne etapy
    }
}