services:
  secret_reader:
    image: alpine:latest
    # Odczytaj zawartość sekretu zamontowanego w domyślnej lokalizacji i wyświetl
    command: sh -c 'echo "Odczytuję sekret..."; cat /run/secrets/app_secret; echo "\nSekret odczytany."; sleep infinity'
    secrets:
      # Nadaj tej usłudze dostęp do sekretu 'app_secret'
      - app_secret

# Definicja sekretu na najwyższym poziomie
secrets:
  app_secret:
    # Określ źródło sekretu - plik na hoście
    file: ./my_secret_data.txt
