services:
  secret_holder:
    image: alpine:latest
    # Ta usługa spróbuje odczytać oba sekrety
    command: >
      sh -c 'echo "--- Holder Service (powinien widzieć oba) ---"; 
      echo -n "User Secret: "; 
      cat /run/secrets/user_secret || echo "BRAK DOSTĘPU"; 
      echo -n "Password Secret: "; 
      cat /run/secrets/pass_secret || echo "BRAK DOSTĘPU"; 
      sleep infinity'
    secrets:
      # Przyznaj dostęp do obu sekretów
      - user_secret
      - pass_secret

  secret_user:
    image: alpine:latest
    # Ta usługa spróbuje odczytać oba sekrety
    command: >
      sh -c 'echo "--- User Service (powinien widzieć tylko user) ---"; 
      echo -n "User Secret: "; 
      cat /run/secrets/user_secret || echo "BRAK DOSTĘPU"; 
      echo -n "Password Secret: "; 
      cat /run/secrets/pass_secret || echo "BRAK DOSTĘPU"; 
      sleep infinity'
    secrets:
      # Przyznaj dostęp TYLKO do sekretu użytkownika
      - user_secret

# Definicje sekretów
secrets:
  user_secret:
    file: ./user.txt
  pass_secret:
    file: ./password.txt
