services:
  builder_service:
    build:
      context: . # Użyj bieżącego katalogu
      dockerfile: Dockerfile # Wskaż plik Dockerfile
      secrets:
        # Udostępnij sekret 'build_api_key' procesowi budowania
        - build_api_key
    # image: my-built-app # Opcjonalnie otaguj wynikowy obraz

# Definicja sekretu na najwyższym poziomie
secrets:
  build_api_key:
    # Źródłem jest zmienna środowiskowa na hoście budującym
    environment: MY_BUILD_KEY